workflows:
  android-kotlin:
    name: Android AutoClicker
    max_build_duration: 10
    environment: {}
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
